# Generated by Django 4.2.4 on 2025-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employe',
            new_name='employee',
        ),
    ]
